### ISSUE TITLE
Lower the max speed

### ISSUE THREAD

**Issue by re3Dprinting** [re3Dprinting/Gigabot-4.2.x#2]
### Description

Lower the max speed 

1. Change in Gigabot.h
 #define DEFAULT_MAX_FEEDRATE          { 150, 150, 4, 60 }
to: 
#define DEFAULT_MAX_FEEDRATE          { 125, 125, 4, 60 }

**Comment by ghost** [comment]
This is changed in firmware 4.2.4 by Matthew. Values are below:

Gigabot: M203 X100.00 Y100.00 Z4.00 E60.00	;Maximum feedrates (units/s)

Terabot: M203 X120.00 Y120.00 Z4.00 E10.00	;Maximum feedrates (units/s)
